version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bharat_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bharat_sahayak
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: bharat_api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/bharat_sahayak
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: